
# cargo-vet config file

[cargo-vet]
version = "0.7"

[policy.quiet-stroll]
audit-as-crates-io = true

[[exemptions.async-stream]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.async-stream-impl]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.61"
criteria = "safe-to-deploy"

[[exemptions.atomic]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.binascii]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.3.2"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.78"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.cookie]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.13"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-queue]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.14"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.13.4"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.13.4"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.13.4"
criteria = "safe-to-deploy"

[[exemptions.devise]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.devise_codegen]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.devise_core]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.dyn-clone]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.encoding_rs]]
version = "0.8.31"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.errno-dragonfly]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.figment]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.generator]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.glob]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.15"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.23"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.2"
criteria = "safe-to-deploy"

[[exemptions.inlinable_string]]
version = "0.1.15"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.io-lifetimes]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.is-terminal]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.jwalk]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.146"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.17"
criteria = "safe-to-deploy"

[[exemptions.loom]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.matchers]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.multer]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.okapi]]
version = "0.7.0-rc.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.overload]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.pear]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.pear_codegen]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.60"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2-diagnostics]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2-diagnostics]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.quiet-stroll]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.28"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.6.1"
criteria = "safe-to-deploy"

[[exemptions.rayon-core]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.ref-cast]]
version = "1.0.14"
criteria = "safe-to-deploy"

[[exemptions.ref-cast-impl]]
version = "1.0.14"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.7.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.28"
criteria = "safe-to-deploy"

[[exemptions.remove_dir_all]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.rocket]]
version = "0.5.0-rc.3"
criteria = "safe-to-deploy"

[[exemptions.rocket_codegen]]
version = "0.5.0-rc.3"
criteria = "safe-to-deploy"

[[exemptions.rocket_http]]
version = "0.5.0-rc.3"
criteria = "safe-to-deploy"

[[exemptions.rocket_okapi]]
version = "0.8.0-rc.3"
criteria = "safe-to-deploy"

[[exemptions.rocket_okapi_codegen]]
version = "0.8.0-rc.3"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.37.20"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.schemars]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.schemars_derive]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.scoped-tls]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.152"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.152"
criteria = "safe-to-deploy"

[[exemptions.serde_derive_internals]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.91"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.stable-pattern]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.state]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.107"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.24.2"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "1.8.2"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.11"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.5.10"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.37"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.ubyte]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.uncased]]
version = "0.9.7"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.unicode-xid]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.39.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.42.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.39.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.39.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.39.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.39.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.39.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "0.5.1"
criteria = "safe-to-deploy"
